### ISSUE TITLE
XATTR's / HFS extended attributes not being written.

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#1]
We need to ensure the movies output by CleanRoom have the spotlight matter data embedded in them as expected. See https://github.com/Synopsis/Synopsis-Analyzer/blob/master/Synopsis/Synopsis/Deprecated/MetadataWriterTranscodeOperation.m#L844

**Comment by mrRay** [comment]
added in 37f2b7cb2f74caf92af8eb82edef931db64af0d6

**Comment by vade** [comment]
### Awesome ill check this out shortly!

**Comment by vade** [comment]
wow so bold!
