### ISSUE TITLE
Thumbnail generation for large movies is slow / synchronous.

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#2]
Looks like for every movie we are trying to spool up a thumbnail image when making the session. This will be slow. Ideally, we should asynchronously build these on demand, when the particular table row / image view comes into the display.

**Comment by mrRay** [comment]
fixed- still generating thumbs up-front, but doing it async and in parallel so it's stupid-fast.  6d121800e78754b664bfb3003920d5fb43a80df4
