### ISSUE TITLE
remove support for mp4s

### ISSUE THREAD

**Issue by mrRay** [Synopsis/SynopsisCleanRoom#24]
according to apple DTS, AVFoundation isn't capable of applying tags longer than four characters to metadata tracks on mp4 containers.

**Comment by vade** [comment]
To be clear, we are removing support for writing MP4 with boxed metadata - not for reading obviously?

**Comment by mrRay** [comment]
correct, 4e6e75aea48e5b073594e1c117d8b1921550d996
