### ISSUE TITLE
NSTableView animations

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#26]
We should have nice clean insertion and deletion animations when objects are added / removed into the NSTableView.

**Comment by mrRay** [comment]
done, but a word of caution: this breaks the MVC paradigm with NSOutlineView, as it forces you to track the data source contents and the views for the data source contents separately.  the upshot of this is that bugs in the NSOutlineViewDelegate/DataSource implementations are going to be trickier for users to report, as what they see is no longer necessarily an accurate representation of the underlying model.
