### ISSUE TITLE
Inspector UI tweaks / ideas

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#28]
Have been pondering the Session Inspector UI.

It might make sense to remove the checkbox and the button to bring up a sheet for file access, and instead have a pull down menu for the location which has options in it. 

Mocked it up in IB like so:

<img width="376" alt="Screen Shot 2019-10-28 at 1 54 46 PM" src="https://user-images.githubusercontent.com/65011/67704351-4e3e8000-f98b-11e9-91fb-89145cf8c167.png">
<img width="369" alt="Screen Shot 2019-10-28 at 1 54 39 PM" src="https://user-images.githubusercontent.com/65011/67704352-4e3e8000-f98b-11e9-8b84-798f5e466bb8.png">

"Default" location is the one set in prefs. Im sure there is cleaner language to use, so suggestions welcome there.

Its not perfect but I think its a touch more straightforward? Let me know - im flexible here.

**Comment by mrRay** [comment]
done, c8572b0a591565955e88f458e7cbee2082208472 + 572a99370b310e26e7d329687ca0a78746c9af16
