### ISSUE TITLE
decide whether or not to scrap the op/session script stuff

### ISSUE THREAD

**Issue by mrRay** [Synopsis/SynopsisCleanRoom#35]
it's taking up space and there doesn't really seem to be any interest in finishing it or keeping it around- should i kill it?

**Comment by vade** [comment]
No - don’t kill it. I can work on the python side of things - I’ve been researching Postgres similarity matching in database using native types and think there’s a really nice way to have the analyzer potentially y’all to a dB via functionality like this. 

Def a feature that should stick around. 

   
   

 http://vade.info

**Comment by mrRay** [comment]
d508fa528caecd614d4abc65cf541f82a95d3d1d

okey-doke- i cleaned up the UI items and made them visible again in both the preferences and the session inspector.  grep the source for "SHOULD BE RUNNING A SCRIPT HERE" to find the points at which you'll want to execute the scripts (i'm not sure how you'd like to handle that or what sorts of values you'd like to provide to the scripts on launch).

let me know if there's anything you'd like to change about how/when the scripts are called- right now it's pretty basic (neither per-op nor per-session scripts are accounted for in progress bars at the moment, nor are there any error or warning states to provide the user with feedback if anything goes awry).  i'm guessing you'd find a basic framework for picking scripts to be useful while you suss out the details, and then i can help with finishing work (enums, UI stuff, etc).

plz open another issue if you find it problems with this layout/structure, or when you'd like to pass it off to me for rest of the cleanup/finishing work
