### ISSUE TITLE
Check metadata pass through for movies with existing (older?) Synopsis metadata?

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#4]
Seems like if we have a movie with old Synopsis versioned metadata it gets passed through / and the updated / new metadata is dumped?

Looking into it more but I've definitely seen some 'ghost' metadata for plugins not currently enabled make it through / not get over-written.

**Comment by mrRay** [comment]
fixed, 37f2b7cb2f74caf92af8eb82edef931db64af0d6
