### ISSUE TITLE
Thinking about user experience / first run

### ISSUE THREAD

**Issue by vade** [Synopsis/SynopsisCleanRoom#45]
The first run experience requires the user to already understand what to expect from the app. We dont really explain whats up at all

We chould

* On first run ask if we want the CLI tool to be installed (once we have that sorted haha)
* Present some sort of interstitial / no sessions graphic on the main table view that explains dropping media files to be analyzed is the way to go, just as a prompt

**Comment by mrRay** [comment]
- commit 869de4693ad301f522037ff5c3d350c1fc82f2c1 adds a "drop files here" graphic to the main window if there aren't presently any sessions/ops
- i think the Synopsis-Framework repos will need a static lib target if we want to make a commandline utility?  the alternative (installing Synopsis.framework in the system) seems like it may cause more problems/compatibility issues than it's worth

**Comment by mrRay** [comment]
closing, both issues have already been resolved
